# This playbook deploys WebCert 

- hosts: tomcat
  sudo: yes 
  vars:
    # repo - values: snapshot or release
    repo: release

    # latest release: 3.1.0-b50
    # latest snapshot: 3.1.0-aNNN
    version: 3.1.0-b51
    config_version: master

  roles:
    - app-resources
    - webcert
